; Example snippet generated by snapmaker-u1-heater-off
; THUMBNAIL_BLOCK_END

;Heater off Block
; - extruder (T0) shutdown after layer 120
; - extruder2 (T2) shutdown after layer 845
;End Heater off Block
